[package]
name = "ame"
version = "0.0.0"
authors = [ "jnats <jnats@salyut.one>", "axtlos <axtlos@salyut.one>" ]
edition = "2018"
description = "a fast and efficient aur helper."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
raur = "3.0.1"
runas = "*"
ansi_term = "*"
uwuizer = "*"
moins = "*"
regex = "*"
toml_edit = "*"
toml = "*"
bytes = "*"
nix = "*"
clap = "*"