[package]
name = "ame"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
git2 = "*"
serde_json = "*"
ureq = "*"
json = "*"
cargo = "*"
curl = "*"