[package]
name = "ame"
version = "2.0.0"
authors = [ "jnats <jnats@salyut.one>", "axtlos <axtlos@salyut.one>" ]
edition = "2018"
description = "a fast and efficient aur helper."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
git2 = "*"
raur = "2.0.2"
runas = "*"
toml = "*"
serde = "*"