[package]
name = "Amethyst"
version = "3.0.0"
authors = [ "jnats <michal@tar.black>", "axtlos <axtlos@tar.black>" ]
edition = "2021"
description = "A fast and efficient aur helper."
license-file = "LICENSE.md"

[[bin]]
name = "ame"
path = "src/main.rs"

[dependencies]
clap = { version = "2.34.0", default-features = false, features = [ "suggestions"] }
regex = { version = "1.5.4", default-features = false, features = [ "std" ] }
runas = "0.2.1"
rusqlite = { version = "0.26.3", default-features = false }
reqwest = { version = "0.11.7", default-features = false, features = [ "blocking", "json", "default-tls" ] }
serde = { version = "1.0.90", default-features = false, features = [ "derive", "serde_derive" ] }